export

include Makefile.Common

#//////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Source Files
#//////////////////////////////////////////////////////////////////////////////////////////////////////////////
# Add ARM-CMSIS
DEFINES += -DARM_MATH_LOOPUNROLL

INCLUDE_FILES += -IDrivers/CMSIS-DSP/Include

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/CommonTables/arm_const_structs.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/CommonTables/arm_common_tables.c

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/StatisticsFunctions/arm_max_f32.c

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/ComplexMathFunctions/arm_cmplx_mag_f32.c

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c

C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/TransformFunctions/arm_cfft_init_f32.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/TransformFunctions/arm_cfft_f32.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/TransformFunctions/arm_cfft_radix8_f32.c
C_SOURCE_FILES += Drivers/CMSIS-DSP/Source/TransformFunctions/arm_bitreversal2.c
#//////////////////////////////////////////////////////////////////////////////////////////////////////////////

.PHONY: all run_inner_make

all: run_inner_make

run_inner_make:
	$(MAKE) -C $(LIBDAISY_DIR)